### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by galandetsv** [dima-bzz/hd.rustem#13]
Добрый день! При попытке приложить файл pdf возникает ошибка:

2VM581:3 Uncaught TypeError: Cannot read property 'replace' of undefined
    at eval (eval at b (http://192.168.132.200/helpdesk/js/tmpl.min.js:1:74), <anonymous>:3:226)
    at http://192.168.132.200/helpdesk/js/tmpl.min.js:1:253
    at http://192.168.132.200/helpdesk/js/tmpl.min.js:1:253
    at t.(anonymous function).(anonymous function)._renderTemplate (http://192.168.132.200/helpdesk/js/jquery.fileupload-ui.js:487:26)
    at t.(anonymous function).(anonymous function)._renderTemplate (http://192.168.132.200/helpdesk/js/jquery-ui-1.10.4.custom.min.js:6:5029)
    at t.(anonymous function).(anonymous function)._renderDownload (http://192.168.132.200/helpdesk/js/jquery.fileupload-ui.js:512:25)
    at t.(anonymous function).(anonymous function)._renderDownload (http://192.168.132.200/helpdesk/js/jquery-ui-1.10.4.custom.min.js:6:5029)
    at n.fn.init.<anonymous> (http://192.168.132.200/helpdesk/js/jquery.fileupload-ui.js:185:49)
    at j (http://192.168.132.200/helpdesk/js/jquery-1.11.0.min.js:2:27136)
    at Object.fireWith [as resolveWith] (http://192.168.132.200/helpdesk/js/jquery-1.11.0.min.js:2:27949)
(anonymous) @ VM581:3
(anonymous) @ tmpl.min.js:1
(anonymous) @ tmpl.min.js:1
_renderTemplate @ jquery.fileupload-ui.js:487
(anonymous) @ jquery-ui-1.10.4.custom.min.js:6
_renderDownload @ jquery.fileupload-ui.js:512
(anonymous) @ jquery-ui-1.10.4.custom.min.js:6
(anonymous) @ jquery.fileupload-ui.js:185
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
(anonymous) @ jquery.fileupload-ui.js:567
dispatch @ jquery-1.11.0.min.js:3
r.handle @ jquery-1.11.0.min.js:3

Вы не сталкивались с такой проблемой?  
ссылка на файл: https://yadi.sk/d/Jmt8h0HG3RKmKz

**Comment by dima-bzz** [comment]
@galandetsv Добрый день. Нет с такой ошибкой не сталкивался. Проверил с вашем файлом все работает.
